# Tensorflow_Basic
Tensorflow에서 Tensor는 Rank라는 차원 단위로 표현된다.
<br>
- Rank 0 : Scalar
- Rank 1 : Vector
- Rank 2 : Matrix
- Rank 3 : 3-Tensor
- Rank n : n-Tensor

In [1]:
# import library
import tensorflow as tf

In [2]:
# Check the version
tf.__version__

'2.5.0'

- Constant : 상수
- Variable : 변수
- Placeholder : 심볼릭 변수
---

## Tensor 정의
### (1) Scalar
1개의 값만 존재한다.

In [3]:
rank_0_tensor = tf.constant(4)
rank_0_tensor # scalar로 구성된 tensor를 출력

<tf.Tensor: shape=(), dtype=int32, numpy=4>

```Python
# tf.print() : 값 출력
```

In [4]:
tf.print(rank_0_tensor)

4


### (2) Vector
1차원 행렬이다.

In [5]:
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
tf.print(rank_1_tensor)

[2 3 4]


### (3) Matrix
2차원 행렬이다.

In [6]:
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4]], dtype=tf.float16)
tf.print(rank_2_tensor)

[[1 2]
 [3 4]]


### (4) 3-Tensor
3차원 행렬이며, n차원도 가능하다.

In [7]:
rank_3_tensor = tf.constant([
    [[0, 1, 2, 3, 4],
     [5, 6, 7, 8, 9]],
    [[10, 11, 12, 13, 14],
     [15, 16, 17, 18, 19]],
    [[20, 21, 22, 23, 24],
     [25, 26, 27, 28, 29]],])

tf.print(rank_3_tensor)

[[[0 1 2 3 4]
  [5 6 7 8 9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]


---
## Tensor의 연산
덧셈, 요소별 곱셈 및 행렬 곱셈을 포함하여, 텐서에 대한 기본 수학을 수행할 수 있다.

```Python
# tf.add(x, y) : 덧셈
# tf.subtract(x, y) : 뺄셈
# tf.multiply(x, y) : 곱셈
# tf.truediv(x, y) : 나눗셈의 몫
# tf.mod(x, y) : 나눗셈의 나머지
# tf.abs(x, y) : 절댓값
```

In [8]:
# 상수의 덧셈
a = tf.constant(2)
b = tf.constant(3)
c = tf.add(a, b)
tf.print(c)

5


```Python
# tf.compat.v1.global_variables_initializer() : 변수 초기화를 위한 작업
```

In [9]:
# 변수의 덧셈
a = tf.Variable(5)
b = tf.Variable(4)
c = tf.add(a, b)
initial = tf.compat.v1.global_variables_initializer()
initial
tf.print(c)

9


In [10]:
tf.print(tf.add(a, b))
tf.print(tf.subtract(a, b))
tf.print(tf.multiply(a, b))
tf.print(tf.truediv(a, b))

9
1
20
1.25
